### ISSUE TITLE
Create PowerBI Report from Project Planning Tool

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/dm_apps#1012]
#Proposed Change/Activity
Learn Power BI and create a PPP Report 

#Why is this important
Learning tools available is important to support Departmental priorities and branch planning

#Updates and Tasks
@stoyelq and @gomezcatalina to do mini-marathon to create a draft tool for Tana 

- [x] Learn PowerBI
- [x] Updates DMs database PPT
- [x] Figure out how to create API to export data
- [x] Create v1.0. of the interactive PPT dashboard

**Comment by stoyelq** [comment]
Anything you can do...
