### ISSUE TITLE
DFO contacts clickable

### ISSUE THREAD

**Issue by davjfish** [dfo-mar-odis/dm_apps#1045]
Hi - would it be possible to make it so that DFO contact names be made clickable so that the user can be brought to that contact's profile page? If helpful, this is where the DFO contact names appear: Interaction details (DFO Maritimes Region liaison, Other DFO Maritimes Region participants/contributors, Last modified by); Committee / Working Group details (DFO Maritimes Region liaison, Other DFO Maritimes region participants/contributors, Last modified by), Organization detail (last modified by), and Person Detail (last modified by).

If this clicking function is not possible, could a change be made instead so that a DFO contact's Section be visible next to their name?

Thanks! _[Added to GitHub by Quentin Stoyel. Ticket created in DM Tickets by Kaitlin Stansfield. Full ticket available [here](http://dmapps/en/dm-tickets/845/view/).]_

### Perceived Effort:
3, but need to confirm that it's okay to share that info.

**Comment by stoyelq** [comment]
- [ ] Interaction details (DFO Maritimes Region liaison
- [ ]  Other DFO Maritimes Region participants/contributors
- [ ] Last modified by); 

- [ ] Committee / Working Group details (DFO Maritimes Region liaison,
- [ ] Other DFO Maritimes region participants/contributors
- [ ]  Last modified by)

- [ ]  Organization detail (last modified by)
- [ ] Person Detail (last modified by).

**Comment by stoyelq** [comment]
Should be okay to make a simple details page with name, email and section.  Sanity check is that if you can see it on Team's, it's probably okay.

**Comment by davjfish** [comment]
Closed by Quentin Stoyel through DM Tickets
