### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by davjfish** [dfo-mar-odis/dm_apps#1055]
Hi. Instead of replicating iHub's approach to reports, I wonder if reporting is something that we can have as part of the main screens for interactions, committees, organizations, and contacts. Meaning, you get to one of the four main pages, apply whatever filters or searches you're interested in, then click either an "Export as PDF" or "Export as Excel workbook" button (located next to the "New" button), then the report is generated that way. Would that work? _[Added to GitHub by Quentin Stoyel. Ticket created in DM Tickets by Kaitlin Stansfield. Full ticket available [here](http://dmapps/en/dm-tickets/836/view/).]_

**Comment by stoyelq** [comment]
### Effort 
8

### When is this done:
When each list view in maret has an export button on it that makes an excel file of the filtered list.

**Comment by stoyelq** [comment]
This is almost done, still need to check the content of the reports (reverse foreign key properties?) and the security level needed for them.

**Comment by davjfish** [comment]
Closed by Quentin Stoyel through DM Tickets
