### ISSUE TITLE
Committee/working group interactions

### ISSUE THREAD

**Issue by davjfish** [dfo-mar-odis/dm_apps#1059]
Hi. When creating a new interaction, instead of having data fields disappear when "Yes" is selected for the Committee or Working Group field, could the following fields please be prepopulated (but still editable) based on whatever information is already on hand for the committee or working group selected: highest level DFO participant; DFO Maritimes Region liaison; Other DFO Maritimes region participants/contributors; main topic(s) of discussion; main species of discussion; lead DFO region; lead DFO Maritimes branch; division; Lead DFO Maritimes Region area office; program; other participating DFO Maritimes Region branches; Other participating DFO regions; lead national sector; participating national headquarters sectors; other participating DFO Maritimes Region area offices; external organization(s); external contacts. _[Added to GitHub by Quentin Stoyel. Ticket created in DM Tickets by Kaitlin Stansfield. Full ticket available [here](http://dmapps/en/dm-tickets/848/view/).]_

**Comment by stoyelq** [comment]
### Perceived effort: 
8

**Comment by davjfish** [comment]
Closed by Quentin Stoyel through DM Tickets
