### ISSUE TITLE
Reports - including multiple pages

### ISSUE THREAD

**Issue by davjfish** [dfo-mar-odis/dm_apps#1080]
Hi - when downloading a report for organizations or contacts, if the total number results after filtering and searching are spread across multiple pages, the "Download Report" function only generates a report of items on the current page. Is it possible to make it so that "Download Report" will include info from all relevant pages? _[Added to GitHub by Quentin Stoyel. Ticket created in DM Tickets by Kaitlin Stansfield. Full ticket available [here](http://dmapps/en/dm-tickets/872/view/).]_

**Comment by stoyelq** [comment]
### Effort
2
