### ISSUE TITLE
Deleting a committee with interactions

### ISSUE THREAD

**Issue by davjfish** [dfo-mar-odis/dm_apps#1081]
Hi - I noticed that if I try to delete a committee with associated interactions, a Server Error comes up. Instead of the Server Error page, could this be changed so that if there are interactions associated with a committee or working group, that second red "Delete" button isn't clickable? So essentially looking for the same functionality as when trying to delete a contact or an organization with related items. _[Added to GitHub by Quentin Stoyel. Ticket created in DM Tickets by Kaitlin Stansfield. Full ticket available [here](http://dmapps/en/dm-tickets/871/view/).]_

**Comment by stoyelq** [comment]
### Effort
3

**Comment by davjfish** [comment]
Closed by Quentin Stoyel through DM Tickets
