### ISSUE TITLE
Unlinking interaction to committee/working group

### ISSUE THREAD

**Issue by davjfish** [dfo-mar-odis/dm_apps#1082]
Hi! I was playing around with the deletion of committees with and without links to interactions. I noticed that a server error comes up when I try to delete a committee that has associated interactions (which makes sense - though I'll submit another ticket asking if this could be changed so that instead the red Delete button just isn't click-able). So I figured I would see what would happen if I edited that interaction to indicate that it is not associated with a committee or working group. I went to the interaction and changed ""Committee or Working Group" to "No". I then went back to the committee and saw that the interaction is still listed there, and still prevents me from deleting that committee. Could it be made so that once I edit an interaction to no longer be associated with a committee or working group, that change is reflected on the committee or working group's page? _[Added to GitHub by Quentin Stoyel. Ticket created in DM Tickets by Kaitlin Stansfield. Full ticket available [here](http://dmapps/en/dm-tickets/870/view/).]_

**Comment by stoyelq** [comment]
### Effort
3

**Comment by davjfish** [comment]
Closed by Quentin Stoyel through DM Tickets
