### ISSUE TITLE
rework models.py for MMU Tools

### ISSUE THREAD

**Issue by oceandatainfosection** [dfo-mar-odis/dm_apps#384]
--change Quantity model to 'Lot' or something like that
--figure out how to incorporate lending into new Quantity model (or not)
--how to use get_initial in views.py to auto load fields with reference info (when adding a quantity, have it automatically fill 'item_name' with current detail_view item) _[Added to GitHub by Elizabeth Thompson. Ticket created in DM Tickets by Elizabeth Thompson. Full ticket available [here](http://dmapps/en/dm-tickets/479/view/).]_

**Comment by davjfish** [comment]
Closed by Elizabeth Thompson through DM Tickets
