### ISSUE TITLE
Create admin group management module

### ISSUE THREAD

**Issue by davjfish** [dfo-mar-odis/dm_apps#503]
-look at travel app to make module for self management of access rights _[Added to GitHub by Elizabeth Thompson. Ticket created in DM Tickets by Elizabeth Thompson. Full ticket available [here](http://dmapps/en/dm-tickets/547/view/).]_

**Comment by upsonp** [comment]
This is something I want too. It's inevitable that some apps are going to have users/groups that will want to manage adding and removing users to their own apps. It's a shame we can't allow access to the django admin console and then grant users rights to only uses parts of it so a whalesdb_admin user could find a user to add to whales and assign them to the whalesdb_user group. CSAS and the staff app (which I should really get back too) are probably also going to want this ability.

I don't think this would be a really complicated shared_models view that could be extended for any app that wants to add or remove users to a list of approved users. It might get more complicated if they want various levels of control for their users as I suspect the staffing app will.

**Comment by upsonp** [comment]
Maybe we should standardize on access group naming. So xxx_access would be a user that can view, but not edit, data in an app, xxx_user would be someone that can edit data and xxx_admin is someone that can use an apps shared_model admin console. Or something to that affect.

**Comment by lizthompson07** [comment]
Just saw your comments Patrick! 

I implemented a copy of what the Travel app did for now, but (as per David's suggestion) subbing out calling the Group object ids directly and using 'get_object_or_404(Group, name="xxx_admin")'.  I had been following the standard of admin users = xxx_admin and edit users = xxx_edit.

I agree it's probably something that would be widely used by apps if available as a shared_model view. It kind of goes back to how I wanted to replicate the django admin console (with clickable boxes and actions, could be changing permissions, or for what I wanted changing the status of an item from 'on order' to 'received'). But I never got further with it and went ahead with the app for now in a simpler way.

**Comment by davjfish** [comment]
Closed by Elizabeth Thompson through DM Tickets
