### ISSUE TITLE
Whales: Error when generating reports with missing data

### ISSUE THREAD

**Issue by davjfish** [dfo-mar-odis/dm_apps#780]
I just discovered that I am getting a server error when trying to generate a report that includes the year 2019. I think this probably has to do with the fact that the datasets added for two deployments in 2019 (COC_2019_10 and SFD_2019_10) have empty fields. We obtained no usable recordings from these deployments so I did not enter in-water start and end dates. If possible, I would like to be able to generate reports that still include these deployments, and just add "NA" to any report fields where data are missing.

A related but slightly different issue - I can generate a report for the year 2020 with no error, but it creates an empty table. I have entered deployment, station, and equipment information for several deployments in 2020, but the recovery event and dataset information are not yet entered since these deployments are still in the water. Again, would it be possible to generate a report that includes partially entered deployments and fills in "NA" where any of the report fields are still missing? _[Added to GitHub by Patrick Upson. Ticket created in DM Tickets by Joy Stanistreet. Full ticket available [here](http://dmapps/en/dm-tickets/642/view/).]_

**Comment by upsonp** [comment]
The issue with the 2020 query was related to nothing from 2020 has datasets associated with the deployments. I've factored out anything not related to a dataset and the dataset data shows up as NA if there is no dataset for a deployment.

**Comment by davjfish** [comment]
Closed by Patrick Upson through DM Tickets
